version: '3.8'

services:
  # ========================================
  # Trading Bot Instance 1 (config_1.py)
  # ========================================
  trader-1:
    build: .
    container_name: titan-trader-1
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_1.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 10 (config_10.py)
  # ========================================
  trader-10:
    build: .
    container_name: titan-trader-10
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_10.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 11 (config_11.py)
  # ========================================
  trader-11:
    build: .
    container_name: titan-trader-11
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_11.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 12 (config_12.py)
  # ========================================
  trader-12:
    build: .
    container_name: titan-trader-12
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_12.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 13 (config_13.py)
  # ========================================
  trader-13:
    build: .
    container_name: titan-trader-13
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_13.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 2 (config_2.py)
  # ========================================
  trader-2:
    build: .
    container_name: titan-trader-2
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_2.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 3 (config_3.py)
  # ========================================
  trader-3:
    build: .
    container_name: titan-trader-3
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_3.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 4 (config_4.py)
  # ========================================
  trader-4:
    build: .
    container_name: titan-trader-4
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_4.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 5 (config_5.py)
  # ========================================
  trader-5:
    build: .
    container_name: titan-trader-5
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_5.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 6 (config_6.py)
  # ========================================
  trader-6:
    build: .
    container_name: titan-trader-6
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_6.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 7 (config_7.py)
  # ========================================
  trader-7:
    build: .
    container_name: titan-trader-7
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_7.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 8 (config_8.py)
  # ========================================
  trader-8:
    build: .
    container_name: titan-trader-8
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_8.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # ========================================
  # Trading Bot Instance 9 (config_9.py)
  # ========================================
  trader-9:
    build: .
    container_name: titan-trader-9
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_9.py
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

# ========================================
# Network Configuration
# ========================================
networks:
  trading-network:
    driver: bridge
