version: '3.8'
services:
  trader-1:
    build: .
    container_name: titan-trader-1
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/app/configs/config_1.py
    volumes:
      - ./configs:/app/configs:ro
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge